name: clean_code
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons:  
  cupertino_icons: ^1.0.0
  http:
  provider:  

dev_dependencies:
  flutter_test:
    sdk: flutter
  test:
  mockito:
  faker:  

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - lib/ui/assets/
  
flutter_icons:
  ios: true
  android: true
  image_path_android: 'lib/ui/assets/icon/android.png'
  image_path_ios: 'lib/ui/assets/icon/ios.png'
  adaptive_icon_background: 'lib/ui/assets/icon/background.png'
  adaptive_icon_foreground: 'lib/ui/assets/icon/foreground.png'